# file for the ci on mutation++

build:
  stage: build
  before_script:
    - apt-get install -y cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - debian_base

build:
  stage: build
  before_script:
    - yum -i -y cmake
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - fedora_base

#test:
#  stage: test
#  script:
#    - checkmix air11
#  artifacts:
#    paths:
#      - tests/
