# file for the ci on mutation++

build-debian:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - debian8

build-ubuntu:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - ubuntu-lts

build-fedora:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - fedora24

build-centos:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - centos7
#test:
#  stage: test
#  script:
#    - checkmix air11
#  artifacts:
#    paths:
#      - tests/
