# file for the ci on mutation++

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - linux

#test:
#  stage: test
#  script:
#    - checkmix air11
#  artifacts:
#    paths:
#      - tests/
