# file for the ci on mutation++

build-debian:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - debian8

build-ubuntu:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - ubuntu-lts

build-fedora:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - fedora24

build-centos:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - centos7

build-macos:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make install

  tags:
    - macOS

test-macos:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - echo $MPP_DATA_DIRECTORY
    - export PATH=$PWD/install/bin:$PATH
    - echo $PATH
    - export DYLD_LIBRARY_PATH=$PWD/install/lib:$DYLD_LIBRARY_PATH
    - echo $DYLD_LIBRARY_PATH
#    - checkmix air11
  tags:
    - macOS

test-centos:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - echo $MPP_DATA_DIRECTORY
    - export PATH=$PWD/install/bin:$PATH
    - echo $PATH
    - export LD_LIBRARY_PATH="path_to_mutation++_directory"/install/lib:$LD_LIBRARY_PATH
    - echo $LD_LIBRARY_PATH
    - checkmix air11
  tags:
    - centos7

test-fedora:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - echo $MPP_DATA_DIRECTORY
    - export PATH=$PWD/install/bin:$PATH
    - echo $PATH
    - export LD_LIBRARY_PATH="path_to_mutation++_directory"/install/lib:$LD_LIBRARY_PATH
    - echo $LD_LIBRARY_PATH
    - checkmix air11
  tags:
    - fedora24

test-debian:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - echo $MPP_DATA_DIRECTORY
    - export PATH=$PWD/install/bin:$PATH
    - echo $PATH
    - export LD_LIBRARY_PATH="path_to_mutation++_directory"/install/lib:$LD_LIBRARY_PATH
    - echo $LD_LIBRARY_PATH
    - checkmix air11
  tags:
    - debian8

test-ubuntu:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - echo $MPP_DATA_DIRECTORY
    - export PATH=$PWD/install/bin:$PATH
    - echo $PATH
    - export LD_LIBRARY_PATH="path_to_mutation++_directory"/install/lib:$LD_LIBRARY_PATH
    - echo $LD_LIBRARY_PATH
    - checkmix air11
  tags:
    - ubuntu-lts

# new commit because of error
#test:
#  stage: test
#  script:
#    - checkmix air11
#  artifacts:
#    paths:
#      - tests/
