# file for the ci on mutation++

build:debian:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - ci_implement
  tags:
    - debian8

build:ubuntu:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - ci_implement
  tags:
    - ubuntu-lts

build:fedora:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - ci_implement
  tags:
    - fedora24

build:centos:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - ci_implement
  tags:
    - centos7

build:macos:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - ci_implement
  tags:
    - macOS

test:macos:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - export PATH=$PWD/install/bin:$PATH
    - export DYLD_LIBRARY_PATH=$PWD/install/lib:$DYLD_LIBRARY_PATH
    - cd build/
    - ctest -VV
  dependencies:
    - build:macos
  only:
    - master
    - ci_implement
  tags:
    - macOS

test:centos:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - export PATH=$PWD/install/bin:$PATH
    - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH
    - cd build/
    - ctest -VV
  dependencies:
    - build:centos
  only:
    - master
    - ci_implement
  tags:
    - centos7

test:fedora:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - export PATH=$PWD/install/bin:$PATH
    - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH
    - cd build/
    - ctest -VV
  dependencies:
    - build:fedora
  only:
    - master
    - ci_implement
  tags:
    - fedora24

test:debian:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - export PATH=$PWD/install/bin:$PATH
    - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH
    - cd build/
    - ctest -VV
  dependencies:
    - build:debian
  only:
    - master
    - ci_implement
  tags:
    - debian8

test:ubuntu:
  stage: test
  script:
    - export MPP_DATA_DIRECTORY=$PWD/data
    - export PATH=$PWD/install/bin:$PATH
    - export LD_LIBRARY_PATH=$PWD/install/lib:$LD_LIBRARY_PATH
    - cd build/
    - ctest -VV
  dependencies:
    - build:ubuntu
  only:
    - master
    - ci_implement
  tags:
    - ubuntu-lts
