build:debian:
  stage: build
  script:
    - export MPP_DIRECTORY=$PWD
    - python scripts/install_dependencies.py -j 1
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - merge-requests
  tags:
    - debian9

build:ubuntu:
  stage: build
  script:
    - export MPP_DIRECTORY=$PWD
    - python scripts/install_dependencies.py -j 1
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - merge-requests
  tags:
    - ubuntu-lts

build:fedora:
  stage: build
  script:
    - export MPP_DIRECTORY=$PWD
    - python scripts/install_dependencies.py -j 1
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - merge-requests
  tags:
    - fedora24

build:centos:
  stage: build
  script:
    - export MPP_DIRECTORY=$PWD
    - python scripts/install_dependencies.py -j 1 --cmd_cmake cmake3
    - mkdir build
    - cd build
    - cmake3 -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - merge-requests
  tags:
    - centos7

build:macos:
  stage: build
  script:
    - export MPP_DIRECTORY=$PWD
    - python scripts/install_dependencies.py -j 1
    - mkdir build
    - cd build
    - cmake -DENABLE_TESTING:BOOL=ON ..
    - make install
  artifacts:
    paths:
      - build/
      - install/
  only:
    - master
    - merge-requests
  tags:
    - macOS

test:macos:
  stage: test
  script:
    - export MPP_DIRECTORY=$PWD
    - export MPP_DATA_DIRECTORY=$MPP_DIRECTORY/data
    - export PATH=$MPP_DIRECTORY/install/bin:$PATH
    - export DYLD_LIBRARY_PATH=$MPP_DIRECTORY/install/lib:$DYLD_LIBRARY_PATH
    - cd build/
    - ctest -V
  dependencies:
    - build:macos
  only:
    - master
    - merge-requests
  tags:
    - macOS

test:centos:
  stage: test
  script:
    - export MPP_DIRECTORY=$PWD
    - export MPP_DATA_DIRECTORY=$MPP_DIRECTORY/data
    - export PATH=$MPP_DIRECTORY/install/bin:$PATH
    - export LD_LIBRARY_PATH=$MPP_DIRECTORY/install/lib:$LD_LIBRARY_PATH
    - cd build/
    - ctest3 -V
  dependencies:
    - build:centos
  only:
    - master
    - merge-requests
  tags:
    - centos7

test:fedora:
  stage: test
  script:
    - export MPP_DIRECTORY=$PWD
    - export MPP_DATA_DIRECTORY=$MPP_DIRECTORY/data
    - export PATH=$MPP_DIRECTORY/install/bin:$PATH
    - export LD_LIBRARY_PATH=$MPP_DIRECTORY/install/lib:$LD_LIBRARY_PATH
    - cd build/
    - ctest -V
  dependencies:
    - build:fedora
  only:
    - master
    - merge-requests
  tags:
    - fedora24

test:debian:
  stage: test
  script:
    - export MPP_DIRECTORY=$PWD
    - export MPP_DATA_DIRECTORY=$MPP_DIRECTORY/data
    - export PATH=$MPP_DIRECTORY/install/bin:$PATH
    - export LD_LIBRARY_PATH=$MPP_DIRECTORY/install/lib:$LD_LIBRARY_PATH
    - cd build/
    - ctest -V
  dependencies:
    - build:debian
  only:
    - master
    - merge-requests
  tags:
    - debian9

test:ubuntu:
  stage: test
  script:
    - export MPP_DIRECTORY=$PWD
    - export MPP_DATA_DIRECTORY=$MPP_DIRECTORY/data
    - export PATH=$MPP_DIRECTORY/install/bin:$PATH
    - export LD_LIBRARY_PATH=$MPP_DIRECTORY/install/lib:$LD_LIBRARY_PATH
    - cd build/
    - ctest -V
  dependencies:
    - build:ubuntu
  only:
    - master
    - merge-requests
  tags:
    - ubuntu-lts
