language: cpp
sudo: false

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install: 
  - export MPP_DIRECTORY=$PWD
  - export MPP_DATA_DIRECTORY=$MPP_DIRECTORY/data
  - export PATH=$MPP_DIRECTORY/install/bin:$PATH
  - export LD_LIBRARY_PATH=$MPP_DIRECTORY/install/lib:$LD_LIBRARY_PATH
  - export DYLD_LIBRARY_PATH=$MPP_DIRECTORY/install/lib:$DYLD_LIBRARY_PATH
  - python scripts/install_dependencies.py -j 1

script: 
  - mkdir build; cd build
  - cmake -DENABLE_TESTING:BOOL=ON ..
  - make install
  - ctest -V

# after_success:
#     # Creating report
#   - cd ${TRAVIS_BUILD_DIR}
#   - lcov --directory . --capture --output-file coverage.info # capture coverage info
#   - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
#   - lcov --list coverage.info #debug info
#   # Uploading report to CodeCov
#   - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
