language: C++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install: 
  - export MPP_DIRECTORY=$PWD
  - python scripts/install_dependencies.py -j 1

script: 
  - mkdir build; cd build
  - cmake -DENABLE_TESTING:BOOL=ON ..
  - make install
