language: C++

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

install: 
  - export MPP_DIRECTORY=$PWD
  - python scripts/install_dependencies.py -j 1

jobs:
  include:
    - stage: Build
        script: 
          - mkdir build; cd build
          - cmake -DENABLE_TESTING:BOOL=ON ..
          - make install
    -stage: Test
        script: ctest -V
